import {Card} from "@prisma/client"
const exampleData: Card[] = [
  {
    id: "1",
    name: "Black Lotus",
    imageUrl: "https://example.com/black-lotus.jpg",
    set: "Alpha",
    quantity: 1,
    foil: false,
    price: 10000,
    collectionId: "collection-1",
  },
  {
    id: "2",
    name: "Mox Sapphire",
    imageUrl: "https://example.com/mox-sapphire.jpg",
    set: "Beta",
    quantity: 1,
    foil: true,
    price: 5000,
    collectionId: "collection-2",
  },
  {
    id: "3",
    name: "Ancestral Recall",
    imageUrl: "https://example.com/ancestral-recall.jpg",
    set: "Unlimited",
    quantity: 1,
    foil: false,
    price: 3000,
    collectionId: "collection-3",
  },
  {
    id: "4",
    name: "Time Walk",
    imageUrl: "https://example.com/time-walk.jpg",
    set: "Revised",
    quantity: 1,
    foil: false,
    price: 2000,
    collectionId: "collection-4",
  },
  {
    id: "5",
    name: "Tarmogoyf",
    imageUrl: "https://example.com/tarmogoyf.jpg",
    set: "Future Sight",
    quantity: 4,
    foil: false,
    price: 100,
    collectionId: "collection-5",
  },
  {
    id: "6",
    name: "Force of Will",
    imageUrl: "https://example.com/force-of-will.jpg",
    set: "Alliances",
    quantity: 3,
    foil: false,
    price: 50,
    collectionId: "collection-6",
  },
  {
    id: "7",
    name: "Jace, the Mind Sculptor",
    imageUrl: "https://example.com/jace-the-mind-sculptor.jpg",
    set: "Worldwake",
    quantity: 2,
    foil: true,
    price: 80,
    collectionId: "collection-7",
  },
  {
    id: "8",
    name: "Snapcaster Mage",
    imageUrl: "https://example.com/snapcaster-mage.jpg",
    set: "Innistrad",
    quantity: 4,
    foil: false,
    price: 30,
    collectionId: "collection-8",
  },
  {
    id: "9",
    name: "Dark Confidant",
    imageUrl: "https://example.com/dark-confidant.jpg",
    set: "Ravnica: City of Guilds",
    quantity: 2,
    foil: true,
    price: 40,
    collectionId: "collection-9",
  },
  {
    id: "10",
    name: "Scalding Tarn",
    imageUrl: "https://example.com/scalding-tarn.jpg",
    set: "Zendikar",
    quantity: 3,
    foil: false,
    price: 50,
    collectionId: "collection-10",
  },
  {
    id: "11",
    name: "Scalding Tarn",
    imageUrl: "https://example.com/scalding-tarn.jpg",
    set: "Zendikar",
    quantity: 3,
    foil: true,
    price: 50,
    collectionId: "collection-10",
  },
  {
    id: "12",
    name: "Scalding Tarn",
    imageUrl: "https://example.com/scalding-tarn.jpg",
    set: "Zendikar",
    quantity: 3,
    foil: false,
    price: 50,
    collectionId: "collection-10",
  },
  {
    id: "13",
    name: "Scalding Tarn",
    imageUrl: "https://example.com/scalding-tarn.jpg",
    set: "Zendikar",
    quantity: 3,
    foil: false,
    price: 50,
    collectionId: "collection-10",
  },
  {
    id: "14",
    name: "Scalding Tarn",
    imageUrl: "https://example.com/scalding-tarn.jpg",
    set: "Zendikar",
    quantity: 3,
    foil: true,
    price: 50,
    collectionId: "collection-10",
  },
];

export default exampleData;
